name: Food Delivery CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-test-package-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          mkdir build
          cp index.html build/
          echo "Build successful"

      - name: Test Application
        run: |
          test -f build/index.html
          echo "Test passed"

      - name: Package Application
        run: |
          zip -r FoodDeliveryApp.zip build/
          echo "Package created"

      - name: Deploy Application
        run: |
          echo "Deployment stage completed"